---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-backend-application
spec:
  selector:
    matchLabels:
      app: login-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: login-backend
    spec:
      containers:
      - name: login-backend
        image: devarangan/login-backend
        envFrom:
        - secretRef:
            name: my-secret
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: login-backend-service
spec:
  selector:
    app: login-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31000
  type: NodePort
